
all: driver newip ipmerge tobu joindb pingall
driver:
	gcc -O3 driver.c list.c -o driver
newip:
	gcc -O3 newip.c -o newip
ipmerge:
	gcc -O3 ipmerge.c list.c -o ipmerge
tobu:
	gcc -O3 tobu.c list.c -o tobu
joindb:
	gcc -O3 joindb.c list.c -o joindb
pingall:
	gcc -O3 pingall.c list.c -o pingall
